trigger:
  - master

pool: 'ubuntu-16.04'

stages:
  - stage: Build_Stage
    displayName:
    jobs:
    - job: BuildNugget
      displayName: Build Nugget packages
      variables:
        BuildConfiguration: release
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
          feedsToUse: 'select'
          arguments: '--configuration $(BuildConfiguration)'