trigger:
  - master

pool: 
  vmImage: 'ubuntu-16.04'

stages:
  - stage: Build_Stage
    displayName:
    jobs:
    - job: BuildNugget
      displayName: Build Nugget packages
      variables:
        BuildConfiguration: release
      steps:
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration $(BuildConfiguration)'
      - task: DotNetCoreCLI@2
        displayName: Pack
        inputs:
          command: 'pack'
          packagesToPack: '**/*.csproj'
          versioningScheme: 'off'
      - task: DotNetCoreCLI@2
        displayName: Pack
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: '91283621-b431-4911-9808-ad6d469d1517/2986e400-6779-424b-9dad-8bd113e784c0'